name: in_dreams
description: "Wishlist app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  firebase_core: ^2.25.3
  firebase_crashlytics: ^3.4.13
  firebase_analytics: ^10.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
