// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDEN8TFAvc0v2WQjYrWIiiOTXCELyXdic',
    appId: '1:399284204047:web:c39930b26fe35387a6297a',
    messagingSenderId: '399284204047',
    projectId: 'in-dreams-34eeb',
    authDomain: 'in-dreams-34eeb.firebaseapp.com',
    storageBucket: 'in-dreams-34eeb.appspot.com',
    measurementId: 'G-B55RT47N7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGmOkfdpcHHjZe3LIUqS5IeYzQdKXTdEs',
    appId: '1:399284204047:android:9957e63d7984f34ba6297a',
    messagingSenderId: '399284204047',
    projectId: 'in-dreams-34eeb',
    storageBucket: 'in-dreams-34eeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa0J56W7zMVRgXA8tLvIEeINlar9roxSs',
    appId: '1:399284204047:ios:130dd445eb4b7a5ca6297a',
    messagingSenderId: '399284204047',
    projectId: 'in-dreams-34eeb',
    storageBucket: 'in-dreams-34eeb.appspot.com',
    iosBundleId: 'ru.fbtw.inDreams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa0J56W7zMVRgXA8tLvIEeINlar9roxSs',
    appId: '1:399284204047:ios:9735413d8640a933a6297a',
    messagingSenderId: '399284204047',
    projectId: 'in-dreams-34eeb',
    storageBucket: 'in-dreams-34eeb.appspot.com',
    iosBundleId: 'ru.fbtw.inDreams.RunnerTests',
  );
}
